# Ramanujan's Theta Functions

## Definitions

Let $a$ and $b$ be integers. Then we define 
$$
f(a,b) := (-q^a;q^{a+b})_{\infty}(-q^b;q^{a+b})_{\infty}(q^{a+b};q^{a+b})_{\infty}.
$$

For the ease of programming, we break the above into two different functions defined below.

$$
sf(a,b) :=  (-q^a;q^{a+b})_{\infty}
$$
and
$$
f_n := (q^{n};q^{n})_{\infty}.
$$

This implies,

$$
f(a,b) \quad = \quad sf(a,b) \; sf(b,a) \; f_{a+b}.
$$

Note that, to avoid confusion, we rename $f(a,b)$ to $ftheta(a,b)$ and $f_n$ to $f(n)$ in the following code. 

In [2]:
%display latex

In [3]:
from sage.modular.etaproducts import qexp_eta
from math import floor
import numpy as np

In [4]:
R.<q> = PowerSeriesRing(ZZ)
f1 = qexp_eta(ZZ[['q']], 1000)

def sf(a, b):
    top = floor((1000-a)/(a+b))
    base = 1
    for r in range(0,top):
        next_term = 1 + q^(a+r*(a+b))
        base = base * next_term
    return base + O(q^1000)

def f(n):
    return f1.V(n)

def ftheta(a,b):
    return sf(a,b)*sf(b,a)*f(a+b)

In [5]:
f_q3_q5 = ftheta(3,5)
f_q3_q5

1 + q^3 + q^5 + q^14 + q^18 + q^33 + q^39 + q^60 + q^68 + q^95 + q^105 + q^138 + q^150 + q^189 + q^203 + q^248 + q^264 + q^315 + q^333 + q^390 + q^410 + q^473 + q^495 + q^564 + q^588 + q^663 + q^689 + q^770 + q^798 + q^885 + q^915 - q^995 - q^997 - q^998 + O(q^1000)

In [6]:
coefficients_list = f_q3_q5.list()

def isodd(number):
    return number % 2 == 1

for i in range(len(coefficients_list)):
    if isodd(i):
        coefficients_list[i] = -coefficients_list[i]

f_nq3_nq5 = R(coefficients_list, 1000)
f_nq3_nq5

1 - q^3 - q^5 + q^14 + q^18 - q^33 - q^39 + q^60 + q^68 - q^95 - q^105 + q^138 + q^150 - q^189 - q^203 + q^248 + q^264 - q^315 - q^333 + q^390 + q^410 - q^473 - q^495 + q^564 + q^588 - q^663 - q^689 + q^770 + q^798 - q^885 - q^915 + q^995 + q^997 - q^998 + O(q^1000)

In [60]:
f4 = f1.V(4)
f8 = f1.V(8)
f16 = f1.V(16)

op345 = (((f_q3_q5/f_nq3_nq5) * (f8^3 / (f4^2 * f16))).list())[:800]


(f_q3_q5/f_nq3_nq5) * (f8^3 / (f4^2 * f16))

1 + 2*q^3 + 2*q^4 + 2*q^5 + 2*q^6 + 4*q^7 + 6*q^8 + 6*q^9 + 6*q^10 + 10*q^11 + 14*q^12 + 14*q^13 + 16*q^14 + 24*q^15 + 30*q^16 + 32*q^17 + 38*q^18 + 50*q^19 + 62*q^20 + 68*q^21 + 78*q^22 + 100*q^23 + 122*q^24 + 134*q^25 + 154*q^26 + 192*q^27 + 228*q^28 + 254*q^29 + 292*q^30 + 352*q^31 + 414*q^32 + 464*q^33 + 528*q^34 + 628*q^35 + 732*q^36 + 818*q^37 + 930*q^38 + 1092*q^39 + 1258*q^40 + 1408*q^41 + 1596*q^42 + 1850*q^43 + 2118*q^44 + 2370*q^45 + 2672*q^46 + 3072*q^47 + 3498*q^48 + 3904*q^49 + 4390*q^50 + 5012*q^51 + 5670*q^52 + 6322*q^53 + 7088*q^54 + 8036*q^55 + 9052*q^56 + 10076*q^57 + 11258*q^58 + 12698*q^59 + 14248*q^60 + 15822*q^61 + 17632*q^62 + 19800*q^63 + 22126*q^64 + 24528*q^65 + 27264*q^66 + 30482*q^67 + 33956*q^68 + 37572*q^69 + 41652*q^70 + 46404*q^71 + 51540*q^72 + 56912*q^73 + 62950*q^74 + 69910*q^75 + 77422*q^76 + 85340*q^77 + 94192*q^78 + 104288*q^79 + 115210*q^80 + 126768*q^81 + 139616*q^82 + 154178*q^83 + 169932*q^84 + 186644*q^85 + 205166*q^86 + 226020*q^87 + 248562*q^88 + 272560*q^89 + 299062*q^90 + 328708*q^91 + 360772*q^92 + 394976*q^93 + 432608*q^94 + 474520*q^95 + 519834*q^96 + 568224*q^97 + 621344*q^98 + 680242*q^99 + 743868*q^100 + 811922*q^101 + 886436*q^102 + 968708*q^103 + 1057570*q^104 + 1152696*q^105 + 1256582*q^106 + 1370922*q^107 + 1494352*q^108 + 1626526*q^109 + 1770608*q^110 + 1928696*q^111 + 2099212*q^112 + 2281920*q^113 + 2480700*q^114 + 2698164*q^115 + 2932614*q^116 + 3183874*q^117 + 3456718*q^118 + 3754504*q^119 + 4075336*q^120 + 4419146*q^121 + 4791930*q^122 + 5197872*q^123 + 5634880*q^124 + 6103216*q^125 + 6610244*q^126 + 7161184*q^127 + 7753934*q^128 + 8389072*q^129 + 9075664*q^130 + 9820370*q^131 + 10621028*q^132 + 11478692*q^133 + 12404674*q^134 + 13407296*q^135 + 14484428*q^136 + 15637984*q^137 + 16881884*q^138 + 18226522*q^139 + 19670156*q^140 + 21215680*q^141 + 22880240*q^142 + 24677032*q^143 + 26604764*q^144 + 28667696*q^145 + 30887152*q^146 + 33279638*q^147 + 35844638*q^148 + 38588482*q^149 + 41537442*q^150 + 44712164*q^151 + 48113594*q^152 + 51750588*q^153 + 55655524*q^154 + 59854496*q^155 + 64350308*q^156 + 69155182*q^157 + 74309312*q^158 + 79845336*q^159 + 85768730*q^160 + 92096448*q^161 + 98878048*q^162 + 106154370*q^163 + 113934928*q^164 + 122242564*q^165 + 131138402*q^166 + 140673860*q^167 + 150863652*q^168 + 161738282*q^169 + 173373516*q^170 + 185833638*q^171 + 199140390*q^172 + 213334606*q^173 + 228509744*q^174 + 244746168*q^175 + 262075410*q^176 + 280551216*q^177 + 300288912*q^178 + 321389314*q^179 + 343896490*q^180 + 367880770*q^181 + 393484908*q^182 + 420834788*q^183 + 449990908*q^184 + 481045324*q^185 + 514174144*q^186 + 549534468*q^187 + 587208736*q^188 + 627316160*q^189 + 670074020*q^190 + 715678752*q^191 + 764240666*q^192 + 815913504*q^193 + 870965840*q^194 + 929642452*q^195 + 992089526*q^196 + 1058505154*q^197 + 1129220530*q^198 + 1204540420*q^199 + 1284657652*q^200 + 1369825660*q^201 + 1460452774*q^202 + 1556918820*q^203 + 1659475420*q^204 + 1768445744*q^205 + 1884333744*q^206 + 2007611512*q^207 + 2138605394*q^208 + 2277726896*q^209 + 2425596856*q^210 + 2582801506*q^211 + 2749762590*q^212 + 2927001508*q^213 + 3115282766*q^214 + 3315334500*q^215 + 3527697936*q^216 + 3753031872*q^217 + 3992278170*q^218 + 4246339232*q^219 + 4515906564*q^220 + 4801811276*q^221 + 5105211972*q^222 + 5427225952*q^223 + 5768734124*q^224 + 6130781088*q^225 + 6514791264*q^226 + 6922147650*q^227 + 7353966952*q^228 + 7811558946*q^229 + 8296674900*q^230 + 8811023560*q^231 + 9356015714*q^232 + 9933291088*q^233 + 10544999942*q^234 + 11193251328*q^235 + 11879823142*q^236 + 12606762144*q^237 + 13376706752*q^238 + 14192258592*q^239 + 15055649976*q^240 + 15969430432*q^241 + 16936836394*q^242 + 17961072050*q^243 + 19044932518*q^244 + 20191588758*q^245 + 21405006032*q^246 + 22689126436*q^247 + 24047442304*q^248 + 25483887996*q^249 + 27003318096*q^250 + 28610578874*q^251 + 30310021160*q^252 + 32106517596*q^253 + 34006008480*q^254 + 36014443216*q^255 + 38137229678*q^256 + 40380393664*q^257 + 427511960

In [8]:
myarr_1_mod_4 = []
for i in range(60):
    myarr_1_mod_4.append(op345[4*i+1])

myarr_3_mod_4 = []
for i in range(60):
    myarr_3_mod_4.append(op345[4*i+3])
    
myarr_1_mod_8 = []
for i in range(30):
    myarr_1_mod_8.append(op345[8*i+1])
    
myarr_3_mod_8 = []
for i in range(30):
    myarr_3_mod_8.append(op345[8*i+3])
    
myarr_5_mod_8 = []
for i in range(30):
    myarr_5_mod_8.append(op345[8*i+5])
    
myarr_7_mod_8 = []
for i in range(30):
    myarr_7_mod_8.append(op345[8*i+7])
    
myarr_1_mod_16 = []
for i in range(15):
    myarr_1_mod_16.append(op345[16*i+1])
    
myarr_3_mod_16 = []
for i in range(15):
    myarr_3_mod_16.append(op345[16*i+3])
    
myarr_5_mod_16 = []
for i in range(15):
    myarr_5_mod_16.append(op345[16*i+5])
    
myarr_7_mod_16 = []
for i in range(15):
    myarr_7_mod_16.append(op345[16*i+7])
    
myarr_9_mod_16 = []
for i in range(15):
    myarr_9_mod_16.append(op345[16*i+9])
    
myarr_11_mod_16 = []
for i in range(15):
    myarr_11_mod_16.append(op345[16*i+11])
    
myarr_13_mod_16 = []
for i in range(15):
    myarr_13_mod_16.append(op345[16*i+13])
    
myarr_15_mod_16 = []
for i in range(15):
    myarr_15_mod_16.append(op345[16*i+15])
    
myarr_1_mod_32 = []
for i in range(10):
    myarr_1_mod_32.append(op345[32*i+1])
    
myarr_2_mod_32 = []
for i in range(12):
    myarr_2_mod_32.append(op345[32*i+2])
    
myarr_3_mod_32 = []
for i in range(8):
    myarr_3_mod_32.append(op345[32*i+3])
    
myarr_5_mod_32 = []
for i in range(8):
    myarr_5_mod_32.append(op345[32*i+5])
    
myarr_7_mod_32 = []
for i in range(8):
    myarr_7_mod_32.append(op345[32*i+7])
    
myarr_9_mod_32 = []
for i in range(8):
    myarr_9_mod_32.append(op345[32*i+9])
    
myarr_11_mod_32 = []
for i in range(8):
    myarr_11_mod_32.append(op345[32*i+11])
    
myarr_13_mod_32 = []
for i in range(8):
    myarr_13_mod_32.append(op345[32*i+13])
    
myarr_14_mod_32 = []
for i in range(12):
    myarr_14_mod_32.append(op345[32*i+1])
    
myarr_15_mod_32 = []
for i in range(8):
    myarr_15_mod_32.append(op345[32*i+15])
    
myarr_17_mod_32 = []
for i in range(9):
    myarr_17_mod_32.append(op345[32*i+17])
    
myarr_19_mod_32 = []
for i in range(8):
    myarr_19_mod_32.append(op345[32*i+19])
    
myarr_21_mod_32 = []
for i in range(8):
    myarr_21_mod_32.append(op345[32*i+21])
    
myarr_23_mod_32 = []
for i in range(8):
    myarr_23_mod_32.append(op345[32*i+23])
    
myarr_25_mod_32 = []
for i in range(8):
    myarr_25_mod_32.append(op345[32*i+25])
    
myarr_27_mod_32 = []
for i in range(8):
    myarr_27_mod_32.append(op345[32*i+27])
    
myarr_29_mod_32 = []
for i in range(8):
    myarr_29_mod_32.append(op345[32*i+29])
    
myarr_31_mod_32 = []
for i in range(8):
    myarr_31_mod_32.append(op345[32*i+31])
    

    

myarr_1_mod_64 = []
for i in range(8):
    myarr_1_mod_64.append(op345[64*i+1])
    
myarr_2_mod_64 = []
for i in range(8):
    myarr_2_mod_64.append(op345[64*i+2])
    
myarr_14_mod_64 = []
for i in range(8):
    myarr_14_mod_64.append(op345[64*i+14])
    
myarr_17_mod_64 = []
for i in range(8):
    myarr_17_mod_64.append(op345[64*i+17])
    
myarr_33_mod_64 = []
for i in range(8):
    myarr_33_mod_64.append(op345[64*i+33])
    
myarr_34_mod_64 = []
for i in range(8):
    myarr_34_mod_64.append(op345[64*i+34])
    
myarr_46_mod_64 = []
for i in range(8):
    myarr_46_mod_64.append(op345[64*i+46])
    
myarr_49_mod_64 = []
for i in range(8):
    myarr_49_mod_64.append(op345[64*i+49])

In [9]:
np.array(myarr_1_mod_4)%4==0

array([ True, False, False, False,  True,  True, False, False,  True,
       False,  True, False,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True, False, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True])

In [10]:
np.array(myarr_3_mod_4)%4==0

array([False,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
       False,  True, False,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True,  True, False,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True])

In [11]:
np.array(myarr_1_mod_8)%4==0

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [12]:
np.array(myarr_3_mod_8)%4==0

array([False, False, False,  True,  True, False,  True, False, False,
       False, False,  True, False, False,  True,  True, False, False,
       False,  True, False, False, False,  True,  True,  True, False,
        True, False,  True])

In [13]:
np.array(myarr_5_mod_8)%4==0

array([False, False,  True, False, False, False, False, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
       False, False,  True, False, False,  True, False,  True,  True,
        True, False,  True])

In [14]:
np.array(myarr_7_mod_8)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [15]:
np.array(myarr_7_mod_8)%8==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True,  True,  True])

In [16]:
8*2+7, op345[23], op345[23]/8

(23, 100, 25/2)

In [17]:
np.array(myarr_1_mod_16)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [18]:
np.array(myarr_1_mod_16)%32==0

array([ True,  True, False,  True, False, False,  True,  True, False,
       False,  True, False,  True, False,  True])

In [19]:
16*2+1, op345[33], op345[33]/32

(33, 464, 29/2)

In [20]:
np.array(myarr_3_mod_16)%4==0

array([False, False,  True,  True, False, False, False,  True, False,
       False, False, False,  True, False, False])

In [21]:
np.array(myarr_5_mod_16)%4==0

array([False,  True, False, False,  True,  True, False, False,  True,
       False,  True, False, False,  True, False])

In [22]:
np.array(myarr_7_mod_16)%8==0

array([False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False,  True])

In [23]:
np.array(myarr_9_mod_16)%8==0

array([False, False,  True, False,  True,  True,  True, False,  True,
       False, False, False, False,  True,  True])

In [24]:
np.array(myarr_11_mod_16)%4==0

array([False,  True, False, False, False,  True, False,  True, False,
        True, False,  True,  True,  True,  True])

In [25]:
np.array(myarr_13_mod_16)%4==0

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False,  True,  True,  True,  True])

In [26]:
np.array(myarr_15_mod_16)%8==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [27]:
np.array(myarr_15_mod_16)%16==0

array([False,  True,  True, False,  True, False, False,  True, False,
       False, False,  True, False,  True,  True])

In [28]:
16*3+15, op345[63], op345[63]/16

(63, 19800, 2475/2)

In [29]:
np.array(myarr_1_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [30]:
np.array(myarr_2_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [31]:
np.array(myarr_2_mod_32)%32==0

array([ True, False,  True,  True, False,  True, False,  True,  True,
       False,  True,  True])

In [32]:
32*1+2, op345[34], op345[34]/32

(34, 528, 33/2)

In [33]:
np.array(myarr_3_mod_32)%16==0

array([False, False, False, False, False, False, False, False])

In [34]:
np.array(myarr_5_mod_32)%16==0

array([False, False, False, False, False, False, False, False])

In [35]:
np.array(myarr_7_mod_32)%16==0

array([False, False, False, False,  True, False, False, False])

In [36]:
np.array(myarr_9_mod_32)%16==0

array([False,  True,  True, False,  True, False, False,  True])

In [37]:
np.array(myarr_11_mod_32)%16==0

array([False, False, False, False, False, False, False,  True])

In [38]:
np.array(myarr_13_mod_32)%16==0

array([False, False, False, False,  True, False,  True,  True])

In [39]:
np.array(myarr_14_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [40]:
np.array(myarr_14_mod_32)%32==0

array([ True, False, False,  True, False,  True,  True,  True,  True,
        True, False,  True])

In [41]:
32*1+14, op345[46], op345[46]/32

(46, 2672, 167/2)

In [42]:
np.array(myarr_15_mod_32)%16==0

array([False,  True,  True, False, False, False, False,  True])

In [43]:
np.array(myarr_17_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [44]:
np.array(myarr_19_mod_32)%16==0

array([False, False, False, False, False, False, False, False])

In [45]:
np.array(myarr_21_mod_32)%16==0

array([False, False, False, False, False, False, False, False])

In [46]:
np.array(myarr_23_mod_32)%16==0

array([False, False, False, False, False, False, False, False])

In [47]:
np.array(myarr_25_mod_32)%16==0

array([False, False,  True, False, False, False,  True, False])

In [48]:
np.array(myarr_27_mod_32)%16==0

array([ True, False, False,  True,  True, False,  True, False])

In [49]:
np.array(myarr_29_mod_32)%16==0

array([False, False,  True,  True, False,  True, False, False])

In [50]:
np.array(myarr_31_mod_32)%16==0

array([ True, False, False,  True, False,  True,  True,  True])

In [51]:
np.array(myarr_1_mod_64)%32==0

array([ True, False, False,  True,  True, False,  True,  True])

In [52]:
np.array(myarr_2_mod_64)%32==0

array([ True,  True, False, False,  True,  True, False, False])

In [53]:
np.array(myarr_14_mod_64)%32==0

array([False, False, False, False,  True, False, False,  True])

In [54]:
np.array(myarr_17_mod_64)%32==0

array([ True, False, False, False,  True,  True,  True,  True])

In [55]:
np.array(myarr_33_mod_64)%32==0

array([False,  True,  True,  True,  True,  True, False, False])

In [56]:
np.array(myarr_34_mod_64)%32==0

array([False,  True,  True,  True, False,  True,  True, False])

In [57]:
np.array(myarr_46_mod_64)%32==0    

array([False, False, False,  True, False, False, False, False])

In [58]:
np.array(myarr_49_mod_64)%32==0

array([ True,  True, False,  True, False, False,  True,  True])