# Ramanujan's Theta Functions

## Definitions

Let $a$ and $b$ be integers. Then we define 
$$
f(a,b) := (-q^a;q^{a+b})_{\infty}(-q^b;q^{a+b})_{\infty}(q^{a+b};q^{a+b})_{\infty}.
$$

For the ease of programming, we break the above into two different functions defined below.

$$
sf(a,b) :=  (-q^a;q^{a+b})_{\infty}
$$
and
$$
f_n := (q^{n};q^{n})_{\infty}.
$$

This implies,

$$
f(a,b) \quad = \quad sf(a,b) \; sf(b,a) \; f_{a+b}.
$$

Note that, to avoid confusion, we rename $f(a,b)$ to $ftheta(a,b)$ and $f_n$ to $f(n)$ in the following code. 

In [56]:
%display latex

In [57]:
from sage.modular.etaproducts import qexp_eta
from math import floor
import numpy as np

In [58]:
R.<q> = PowerSeriesRing(ZZ)
f1 = qexp_eta(ZZ[['q']], 3000)

def sf(a, b):
    top = floor((3000-a)/(a+b))
    base = 1
    for r in range(0,top):
        next_term = 1 + q^(a+r*(a+b))
        base = base * next_term
    return base + O(q^3000)

def f(n):
    return f1.V(n)

def ftheta(a,b):
    return sf(a,b)*sf(b,a)*f(a+b)

In [59]:
f_q3_q5 = ftheta(3,5)
f_q3_q5

1 + q^3 + q^5 + q^14 + q^18 + q^33 + q^39 + q^60 + q^68 + q^95 + q^105 + q^138 + q^150 + q^189 + q^203 + q^248 + q^264 + q^315 + q^333 + q^390 + q^410 + q^473 + q^495 + q^564 + q^588 + q^663 + q^689 + q^770 + q^798 + q^885 + q^915 + q^1008 + q^1040 + q^1139 + q^1173 + q^1278 + q^1314 + q^1425 + q^1463 + q^1580 + q^1620 + q^1743 + q^1785 + q^1914 + q^1958 + q^2093 + q^2139 + q^2280 + q^2328 + q^2475 + q^2525 + q^2678 + q^2730 + q^2889 + q^2943 - q^2995 - q^2997 - q^2998 + O(q^3000)

In [60]:
coefficients_list = f_q3_q5.list()

def isodd(number):
    return number % 2 == 1

for i in range(len(coefficients_list)):
    if isodd(i):
        coefficients_list[i] = -coefficients_list[i]

f_nq3_nq5 = R(coefficients_list, 3000)
f_nq3_nq5

1 - q^3 - q^5 + q^14 + q^18 - q^33 - q^39 + q^60 + q^68 - q^95 - q^105 + q^138 + q^150 - q^189 - q^203 + q^248 + q^264 - q^315 - q^333 + q^390 + q^410 - q^473 - q^495 + q^564 + q^588 - q^663 - q^689 + q^770 + q^798 - q^885 - q^915 + q^1008 + q^1040 - q^1139 - q^1173 + q^1278 + q^1314 - q^1425 - q^1463 + q^1580 + q^1620 - q^1743 - q^1785 + q^1914 + q^1958 - q^2093 - q^2139 + q^2280 + q^2328 - q^2475 - q^2525 + q^2678 + q^2730 - q^2889 - q^2943 + q^2995 + q^2997 - q^2998 + O(q^3000)

In [61]:
f4 = f1.V(4)
f8 = f1.V(8)
f16 = f1.V(16)

op345 = (((f_q3_q5/f_nq3_nq5) * (f8^3 / (f4^2 * f16))).list())[:2800]

In [82]:
myarr_41_mod_82 = []
for i in range(30):
    myarr_41_mod_82.append(op345[82*i+41])
    
myarr_27_mod_81 = []
for i in range(30):
    myarr_27_mod_81.append(op345[81*i+27])
    
myarr_54_mod_81 = []
for i in range(30):
    myarr_54_mod_81.append(op345[81*i+54])
    
myarr_41_mod_120 = []
for i in range(23):
    myarr_41_mod_120.append(op345[120*i+41])
    
myarr_89_mod_120 = []
for i in range(23):
    myarr_89_mod_120.append(op345[120*i+89])
    
myarr_97_mod_120 = []
for i in range(23):
    myarr_97_mod_120.append(op345[120*i+97])
    
myarr_31_mod_62 = []
for i in range(30):
    myarr_31_mod_62.append(op345[62*i+31])
    
myarr_31_mod_93 = []
for i in range(30):
    myarr_31_mod_93.append(op345[93*i+31])
    
myarr_62_mod_93 = []
for i in range(30):
    myarr_62_mod_93.append(op345[93*i+62])
    
myarr_47_mod_94 = []
for i in range(30):
    myarr_47_mod_94.append(op345[94*i+47])

In [83]:
np.array(myarr_41_mod_82)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [84]:
np.array(myarr_27_mod_81)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [85]:
np.array(myarr_54_mod_81)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [86]:
np.array(myarr_41_mod_120)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True])

In [87]:
np.array(myarr_89_mod_120)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True, False,  True,  True])

In [88]:
np.array(myarr_97_mod_120)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [89]:
np.array(myarr_31_mod_62)%32==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [90]:
np.array(myarr_31_mod_93)%32==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [91]:
np.array(myarr_62_mod_93)%32==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [92]:
np.array(myarr_47_mod_94)%64==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [113]:
120*6+41, 120*7+41, 120*8+41

(761, 881, 1001)

In [114]:
op345[761]/16, op345[881]/16, op345[1001]/16

(5070120304609408648, 256022944196178373720, 20087720715969317448489/2)

In [109]:
120*10+89, 120*11+89, 120*12+89

(1289, 1409, 1529)

In [112]:
op345[1289]/16, op345[1409]/16, op345[1529]/16 

(30374617089920099762244361,
 658932816265830174546316986,
 50418547818087552468700969321/4)

In [115]:
120*7+97, 120*8+97, 120*9+97

(937, 1057, 1177)

In [116]:
op345[937]/16, op345[1057]/16, op345[1177]/16

(1459897185669750484221, 51713076441777454122892, 6043053610035576749232417/4)