# Ramanujan's Theta Functions

## Definitions

Let $a$ and $b$ be integers. Then we define 
$$
f(a,b) := (-q^a;q^{a+b})_{\infty}(-q^b;q^{a+b})_{\infty}(q^{a+b};q^{a+b})_{\infty}.
$$

For the ease of programming, we break the above into two different functions defined below.

$$
sf(a,b) :=  (-q^a;q^{a+b})_{\infty}
$$
and
$$
f_n := (q^{n};q^{n})_{\infty}.
$$

This implies,

$$
f(a,b) \quad = \quad sf(a,b) \; sf(b,a) \; f_{a+b}.
$$

Note that, to avoid confusion, we rename $f(a,b)$ to $ftheta(a,b)$ and $f_n$ to $f(n)$ in the following code. 

In [2]:
%display latex

In [3]:
from sage.modular.etaproducts import qexp_eta
from math import floor
import numpy as np

In [4]:
R.<q> = PowerSeriesRing(ZZ)
f1 = qexp_eta(ZZ[['q']], 1000)

def sf(a, b):
    top = floor((1000-a)/(a+b))
    base = 1
    for r in range(0,top):
        next_term = 1 + q^(a+r*(a+b))
        base = base * next_term
    return base + O(q^1000)

def f(n):
    return f1.V(n)

def ftheta(a,b):
    return sf(a,b)*sf(b,a)*f(a+b)

In [5]:
f_q3_q5 = ftheta(3,5)
f_q3_q5

1 + q^3 + q^5 + q^14 + q^18 + q^33 + q^39 + q^60 + q^68 + q^95 + q^105 + q^138 + q^150 + q^189 + q^203 + q^248 + q^264 + q^315 + q^333 + q^390 + q^410 + q^473 + q^495 + q^564 + q^588 + q^663 + q^689 + q^770 + q^798 + q^885 + q^915 - q^995 - q^997 - q^998 + O(q^1000)

In [6]:
coefficients_list = f_q3_q5.list()

def isodd(number):
    return number % 2 == 1

for i in range(len(coefficients_list)):
    if isodd(i):
        coefficients_list[i] = -coefficients_list[i]

f_nq3_nq5 = R(coefficients_list, 1000)
f_nq3_nq5

1 - q^3 - q^5 + q^14 + q^18 - q^33 - q^39 + q^60 + q^68 - q^95 - q^105 + q^138 + q^150 - q^189 - q^203 + q^248 + q^264 - q^315 - q^333 + q^390 + q^410 - q^473 - q^495 + q^564 + q^588 - q^663 - q^689 + q^770 + q^798 - q^885 - q^915 + q^995 + q^997 - q^998 + O(q^1000)

In [7]:
op35 = (((f_q3_q5/f_nq3_nq5)).list())[:800]

In [8]:
myarr_0_mod_2 = []
for i in range(120):
    myarr_0_mod_2.append(op35[2*i])

myarr_1_mod_2 = []
for i in range(120):
    myarr_1_mod_2.append(op35[2*i+1])

myarr_0_mod_4 = []
for i in range(60):
    myarr_0_mod_4.append(op35[4*i])
    
myarr_1_mod_4 = []
for i in range(60):
    myarr_1_mod_4.append(op35[4*i+1])

myarr_2_mod_4 = []
for i in range(60):
    myarr_2_mod_4.append(op35[4*i+2])
    
myarr_3_mod_4 = []
for i in range(60):
    myarr_3_mod_4.append(op35[4*i+3])

myarr_0_mod_8 = []
for i in range(30):
    myarr_0_mod_8.append(op35[8*i])
    
myarr_1_mod_8 = []
for i in range(30):
    myarr_1_mod_8.append(op35[8*i+1])
    
myarr_2_mod_8 = []
for i in range(30):
    myarr_2_mod_8.append(op35[8*i+2])
    
myarr_3_mod_8 = []
for i in range(30):
    myarr_3_mod_8.append(op35[8*i+3])
    
myarr_4_mod_8 = []
for i in range(30):
    myarr_4_mod_8.append(op35[8*i+4])
    
myarr_5_mod_8 = []
for i in range(30):
    myarr_5_mod_8.append(op35[8*i+5])
    
myarr_6_mod_8 = []
for i in range(30):
    myarr_6_mod_8.append(op35[8*i+6])
    
myarr_7_mod_8 = []
for i in range(30):
    myarr_7_mod_8.append(op35[8*i+7])

myarr_0_mod_16 = []
for i in range(15):
    myarr_0_mod_16.append(op35[16*i])
    
myarr_1_mod_16 = []
for i in range(15):
    myarr_1_mod_16.append(op35[16*i+1])
    
myarr_2_mod_16 = []
for i in range(15):
    myarr_2_mod_16.append(op35[16*i+2])
    
myarr_3_mod_16 = []
for i in range(15):
    myarr_3_mod_16.append(op35[16*i+3])
    
myarr_4_mod_16 = []
for i in range(15):
    myarr_4_mod_16.append(op35[16*i+4])
    
myarr_5_mod_16 = []
for i in range(15):
    myarr_5_mod_16.append(op35[16*i+5])
    
myarr_6_mod_16 = []
for i in range(15):
    myarr_6_mod_16.append(op35[16*i+6])
    
myarr_7_mod_16 = []
for i in range(15):
    myarr_7_mod_16.append(op35[16*i+7])
    
myarr_8_mod_16 = []
for i in range(15):
    myarr_8_mod_16.append(op35[16*i+8])
    
myarr_9_mod_16 = []
for i in range(15):
    myarr_9_mod_16.append(op35[16*i+9])
    
myarr_10_mod_16 = []
for i in range(15):
    myarr_10_mod_16.append(op35[16*i+10])
    
myarr_11_mod_16 = []
for i in range(15):
    myarr_11_mod_16.append(op35[16*i+11])
    
myarr_12_mod_16 = []
for i in range(15):
    myarr_12_mod_16.append(op35[16*i+12])
    
myarr_13_mod_16 = []
for i in range(15):
    myarr_13_mod_16.append(op35[16*i+13])
    
myarr_14_mod_16 = []
for i in range(15):
    myarr_14_mod_16.append(op35[16*i+14])
    
myarr_15_mod_16 = []
for i in range(15):
    myarr_15_mod_16.append(op35[16*i+15])

myarr_0_mod_32 = []
for i in range(10):
    myarr_0_mod_32.append(op35[32*i+0])
    
myarr_1_mod_32 = []
for i in range(10):
    myarr_1_mod_32.append(op35[32*i+1])
    
myarr_2_mod_32 = []
for i in range(10):
    myarr_2_mod_32.append(op35[32*i+2])
    
myarr_3_mod_32 = []
for i in range(8):
    myarr_3_mod_32.append(op35[32*i+3])
    
myarr_4_mod_32 = []
for i in range(10):
    myarr_4_mod_32.append(op35[32*i+4])
    
myarr_5_mod_32 = []
for i in range(8):
    myarr_5_mod_32.append(op35[32*i+5])
    
myarr_6_mod_32 = []
for i in range(10):
    myarr_6_mod_32.append(op35[32*i+6])
    
myarr_7_mod_32 = []
for i in range(8):
    myarr_7_mod_32.append(op35[32*i+7])
    
myarr_8_mod_32 = []
for i in range(10):
    myarr_8_mod_32.append(op35[32*i+8])
    
myarr_9_mod_32 = []
for i in range(8):
    myarr_9_mod_32.append(op35[32*i+9])

myarr_10_mod_32 = []
for i in range(8):
    myarr_10_mod_32.append(op35[32*i+10])
    
myarr_11_mod_32 = []
for i in range(8):
    myarr_11_mod_32.append(op35[32*i+11])
    
myarr_12_mod_32 = []
for i in range(8):
    myarr_12_mod_32.append(op35[32*i+12])
    
myarr_13_mod_32 = []
for i in range(8):
    myarr_13_mod_32.append(op35[32*i+13])
    
myarr_14_mod_32 = []
for i in range(8):
    myarr_14_mod_32.append(op35[32*i+14])
    
myarr_15_mod_32 = []
for i in range(8):
    myarr_15_mod_32.append(op35[32*i+15])
    
myarr_16_mod_32 = []
for i in range(8):
    myarr_16_mod_32.append(op35[32*i+16])
    
myarr_17_mod_32 = []
for i in range(9):
    myarr_17_mod_32.append(op35[32*i+17])
    
myarr_18_mod_32 = []
for i in range(8):
    myarr_18_mod_32.append(op35[32*i+18])
    
myarr_19_mod_32 = []
for i in range(8):
    myarr_19_mod_32.append(op35[32*i+19])
    
myarr_20_mod_32 = []
for i in range(8):
    myarr_20_mod_32.append(op35[32*i+20])
    
myarr_21_mod_32 = []
for i in range(8):
    myarr_21_mod_32.append(op35[32*i+21])
    
myarr_22_mod_32 = []
for i in range(8):
    myarr_22_mod_32.append(op35[32*i+22])
    
myarr_23_mod_32 = []
for i in range(8):
    myarr_23_mod_32.append(op35[32*i+23])
    
myarr_24_mod_32 = []
for i in range(8):
    myarr_24_mod_32.append(op35[32*i+24])
    
myarr_25_mod_32 = []
for i in range(8):
    myarr_25_mod_32.append(op35[32*i+25])
    
myarr_26_mod_32 = []
for i in range(8):
    myarr_26_mod_32.append(op35[32*i+26])
    
myarr_27_mod_32 = []
for i in range(8):
    myarr_27_mod_32.append(op35[32*i+27])
    
myarr_28_mod_32 = []
for i in range(8):
    myarr_28_mod_32.append(op35[32*i+28])
    
myarr_29_mod_32 = []
for i in range(8):
    myarr_29_mod_32.append(op35[32*i+29])
    
myarr_30_mod_32 = []
for i in range(8):
    myarr_30_mod_32.append(op35[32*i+30])
    
myarr_31_mod_32 = []
for i in range(8):
    myarr_31_mod_32.append(op35[32*i+31])
        
myarr_7_mod_64 = []
for i in range(8):
    myarr_7_mod_64.append(op35[64*i+7])
    
myarr_23_mod_64 = []
for i in range(8):
    myarr_23_mod_64.append(op35[64*i+23])
    
myarr_39_mod_64 = []
for i in range(8):
    myarr_39_mod_64.append(op35[64*i+39])
    
myarr_55_mod_64 = []
for i in range(8):
    myarr_55_mod_64.append(op35[64*i+55])
    
myarr_2_mod_64 = []
for i in range(8):
    myarr_2_mod_64.append(op35[64*i+2])
    
myarr_34_mod_64 = []
for i in range(8):
    myarr_34_mod_64.append(op35[64*i+34])

In [9]:
np.array(myarr_0_mod_2)%2==0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [10]:
np.array(myarr_1_mod_2)%2==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [11]:
np.array(myarr_0_mod_4)%4==0

array([False,  True,  True, False,  True, False, False,  True,  True,
       False, False, False, False, False,  True,  True,  True,  True,
       False, False, False,  True, False,  True, False, False, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False, False, False,  True, False,  True,  True, False, False,
       False,  True,  True, False,  True, False,  True, False, False,
        True,  True,  True,  True, False, False])

In [12]:
np.array(myarr_1_mod_4)%4==0

array([ True, False, False, False,  True,  True, False, False,  True,
       False,  True, False,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True, False, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True])

In [13]:
np.array(myarr_2_mod_4)%4==0

array([ True, False, False,  True, False, False, False,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True, False, False,  True,  True,  True, False,
        True,  True, False, False,  True,  True, False,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True, False,
       False,  True,  True,  True, False,  True])

In [14]:
np.array(myarr_3_mod_4)%4==0

array([False,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
       False,  True, False,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True,  True, False,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True])

In [15]:
np.array(myarr_0_mod_8)%4==0

array([False,  True,  True, False,  True, False, False,  True,  True,
       False, False, False, False, False,  True,  True,  True,  True,
       False, False, False,  True, False,  True, False, False, False,
        True,  True, False])

In [16]:
np.array(myarr_1_mod_8)%4==0

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [17]:
np.array(myarr_2_mod_8)%4==0

array([ True, False, False, False,  True,  True, False, False,  True,
       False,  True, False,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True, False])

In [18]:
np.array(myarr_3_mod_8)%4==0

array([False, False, False,  True,  True, False,  True, False, False,
       False, False,  True, False, False,  True,  True, False, False,
       False,  True, False, False, False,  True,  True,  True, False,
        True, False,  True])

In [19]:
np.array(myarr_4_mod_8)%4==0

array([ True, False, False,  True, False, False, False,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True, False, False,  True,  True,  True, False,
        True,  True, False])

In [20]:
np.array(myarr_5_mod_8)%4==0

array([False, False,  True, False, False, False, False, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
       False, False,  True, False, False,  True, False,  True,  True,
        True, False,  True])

In [21]:
np.array(myarr_6_mod_8)%4==0

array([False,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
       False,  True, False,  True,  True,  True, False,  True, False,
        True,  True,  True])

In [22]:
np.array(myarr_7_mod_8)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [23]:
np.array(myarr_7_mod_8)%8==0

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True, False,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True])

In [24]:
8*1+7, op35[15], op35[15]/8

(15, 4, 1/2)

In [25]:
np.array(myarr_0_mod_16)%4==0

array([False,  True,  True, False,  True, False, False,  True,  True,
       False, False, False, False, False,  True])

In [26]:
np.array(myarr_1_mod_16)%8==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [27]:
np.array(myarr_1_mod_16)%16==0

array([ True, False, False,  True,  True, False, False,  True, False,
        True,  True, False, False, False, False])

In [28]:
16*1+1, op35[17], op35[17]/16

(17, 8, 1/2)

In [29]:
np.array(myarr_2_mod_16)%4==0

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [30]:
np.array(myarr_3_mod_16)%4==0

array([False, False,  True,  True, False, False, False,  True, False,
       False, False, False,  True, False, False])

In [31]:
np.array(myarr_4_mod_16)%4==0

array([ True, False, False, False,  True,  True, False, False,  True,
       False,  True, False,  True, False,  True])

In [32]:
np.array(myarr_5_mod_16)%4==0

array([False,  True, False, False,  True,  True, False, False,  True,
       False,  True, False, False,  True, False])

In [33]:
np.array(myarr_6_mod_16)%4==0

array([False, False, False,  True,  True, False,  True, False, False,
       False, False,  True, False, False,  True])

In [34]:
np.array(myarr_7_mod_16)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [35]:
np.array(myarr_7_mod_16)%32==0

array([ True, False,  True,  True, False, False, False, False, False,
       False,  True,  True,  True, False, False])

In [36]:
16*1+7, op35[23], op35[23]/32

(23, 16, 1/2)

In [37]:
np.array(myarr_8_mod_16)%4==0

array([ True, False, False,  True, False, False, False,  True,  True,
       False,  True,  True, False,  True, False])

In [38]:
np.array(myarr_9_mod_16)%4==0

array([False, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True])

In [39]:
np.array(myarr_10_mod_16)%4==0

array([False, False,  True, False, False, False, False, False,  True,
        True,  True,  True, False, False, False])

In [40]:
np.array(myarr_11_mod_16)%4==0

array([False,  True, False, False, False,  True, False,  True, False,
        True, False,  True,  True,  True,  True])

In [41]:
np.array(myarr_12_mod_16)%4==0

array([False,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False])

In [42]:
np.array(myarr_13_mod_16)%4==0

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False,  True,  True,  True,  True])

In [43]:
np.array(myarr_14_mod_16)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [44]:
np.array(myarr_14_mod_16)%8==0

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True, False,  True])

In [45]:
16*1+14, op35[30], op35[30]/8

(30, 60, 15/2)

In [46]:
np.array(myarr_15_mod_16)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [47]:
np.array(myarr_0_mod_32)%4==0

array([False,  True,  True, False,  True, False, False,  True,  True,
       False])

In [48]:
np.array(myarr_1_mod_32)%8==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [49]:
np.array(myarr_2_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [50]:
np.array(myarr_2_mod_32)%32==0

array([ True, False,  True,  True, False,  True, False,  True,  True,
       False])

In [51]:
32*1+2, op35[34], op35[34]/32

(34, 80, 5/2)

In [52]:
np.array(myarr_3_mod_32)%4==0

array([False,  True, False, False, False, False,  True, False])

In [53]:
np.array(myarr_4_mod_32)%4==0

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True])

In [54]:
np.array(myarr_5_mod_32)%4==0

array([False, False,  True, False,  True,  True, False, False])

In [55]:
np.array(myarr_6_mod_32)%4==0

array([False, False,  True,  True, False, False, False,  True, False,
       False])

In [56]:
np.array(myarr_7_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [57]:
np.array(myarr_8_mod_32)%4==0

array([ True, False, False, False,  True,  True, False, False,  True,
       False])

In [58]:
np.array(myarr_9_mod_32)%4==0

array([False,  True,  True,  True,  True, False,  True,  True])

In [59]:
np.array(myarr_10_mod_32)%4==0

array([False,  True, False, False,  True,  True, False, False])

In [60]:
np.array(myarr_11_mod_32)%4==0

array([False, False, False, False, False, False,  True,  True])

In [61]:
np.array(myarr_12_mod_32)%4==0

array([False, False, False,  True,  True, False,  True, False])

In [62]:
np.array(myarr_13_mod_32)%4==0

array([False, False,  True, False,  True, False,  True,  True])

In [63]:
np.array(myarr_14_mod_32)%8==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [64]:
np.array(myarr_14_mod_32)%16==0

array([False, False, False, False, False, False, False,  True])

In [91]:
32*1+14, op35[46], op35[46]/16

(46, 328, 41/2)

In [66]:
np.array(myarr_15_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [67]:
np.array(myarr_16_mod_32)%4==0

array([ True, False, False,  True, False, False, False,  True])

In [68]:
np.array(myarr_17_mod_32)%8==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [69]:
np.array(myarr_18_mod_32)%4==0

array([False, False,  True,  True,  True,  True,  True, False])

In [70]:
np.array(myarr_19_mod_32)%4==0

array([False,  True, False,  True, False, False, False, False])

In [71]:
np.array(myarr_20_mod_32)%4==0

array([False, False,  True, False, False, False, False, False])

In [72]:
np.array(myarr_21_mod_32)%4==0

array([ True, False,  True, False, False, False,  True, False])

In [73]:
np.array(myarr_22_mod_32)%4==0

array([False,  True, False, False, False,  True, False,  True])

In [74]:
np.array(myarr_23_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [75]:
np.array(myarr_24_mod_32)%4==0

array([False,  True, False,  True, False,  True,  True,  True])

In [76]:
np.array(myarr_25_mod_32)%4==0

array([False,  True,  True, False,  True,  True,  True,  True])

In [77]:
np.array(myarr_26_mod_32)%4==0

array([False, False, False, False,  True,  True, False,  True])

In [78]:
np.array(myarr_27_mod_32)%4==0

array([ True, False,  True,  True,  True,  True,  True, False])

In [79]:
np.array(myarr_28_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [80]:
np.array(myarr_28_mod_32)%8==0

array([ True, False,  True,  True,  True,  True,  True, False])

In [81]:
32*1+28, op35[60], op35[60]/8

(60, 1076, 269/2)

In [82]:
np.array(myarr_29_mod_32)%4==0

array([False, False,  True,  True, False,  True,  True,  True])

In [83]:
np.array(myarr_30_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [84]:
np.array(myarr_31_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [85]:
np.array(myarr_7_mod_64)%32==0

array([ True, False, False,  True, False, False, False,  True])

In [86]:
np.array(myarr_23_mod_64)%32==0

array([False, False, False, False, False,  True, False,  True])

In [87]:
np.array(myarr_39_mod_64)%32==0

array([ True, False,  True, False, False, False, False,  True])

In [88]:
np.array(myarr_55_mod_64)%32==0

array([ True, False,  True, False,  True,  True,  True, False])

In [89]:
np.array(myarr_2_mod_64)%32==0

array([ True,  True, False, False,  True,  True, False, False])

In [90]:
np.array(myarr_34_mod_64)%32==0

array([False,  True,  True,  True, False,  True,  True, False])