# Ramanujan's Theta Functions

## Definitions

Let $a$ and $b$ be integers. Then we define 
$$
f(a,b) := (-q^a;q^{a+b})_{\infty}(-q^b;q^{a+b})_{\infty}(q^{a+b};q^{a+b})_{\infty}.
$$

For the ease of programming, we break the above into two different functions defined below.

$$
sf(a,b) :=  (-q^a;q^{a+b})_{\infty}
$$
and
$$
f_n := (q^{n};q^{n})_{\infty}.
$$

This implies,

$$
f(a,b) \quad = \quad sf(a,b) \; sf(b,a) \; f_{a+b}.
$$

Note that, to avoid confusion, we rename $f(a,b)$ to $ftheta(a,b)$ and $f_n$ to $f(n)$ in the following code. 

In [2]:
%display latex

In [3]:
from sage.modular.etaproducts import qexp_eta
from math import floor
import numpy as np

In [4]:
R.<q> = PowerSeriesRing(ZZ)
f1 = qexp_eta(ZZ[['q']], 500)

def sf(a, b):
    top = floor((500-a)/(a+b))
    base = 1
    for r in range(0,top):
        next_term = 1 + q^(a+r*(a+b))
        base = base * next_term
    return base + O(q^500)

def f(n):
    return f1.V(n)

def ftheta(a,b):
    return sf(a,b)*sf(b,a)*f(a+b)

In [5]:
f_q_q7 = ftheta(1,7)
f_q_q7

1 + q + q^7 + q^10 + q^22 + q^27 + q^45 + q^52 + q^76 + q^85 + q^115 + q^126 + q^162 + q^175 + q^217 + q^232 + q^280 + q^297 + q^351 + q^370 + q^430 + q^451 - q^495 - q^496 - q^497 - q^498 + O(q^500)

In [6]:
coefficients_list = f_q_q7.list()

def isodd(number):
    return number % 2 == 1

for i in range(len(coefficients_list)):
    if isodd(i):
        coefficients_list[i] = -coefficients_list[i]

f_nq_nq7 = R(coefficients_list, 500)
f_nq_nq7

1 - q - q^7 + q^10 + q^22 - q^27 - q^45 + q^52 + q^76 - q^85 - q^115 + q^126 + q^162 - q^175 - q^217 + q^232 + q^280 - q^297 - q^351 + q^370 + q^430 - q^451 + q^495 - q^496 + q^497 - q^498 + O(q^500)

In [7]:
f4 = f1.V(4)
f8 = f1.V(8)
f16 = f1.V(16)

op147 = (((f_q_q7/f_nq_nq7) * (f8^3 / (f4^2 * f16))).list())[:300]

In [8]:
myarr_1_mod_4 = []
for i in range(60):
    myarr_1_mod_4.append(op147[4*i+1])

myarr_3_mod_4 = []
for i in range(60):
    myarr_3_mod_4.append(op147[4*i+3])
    
myarr_1_mod_8 = []
for i in range(30):
    myarr_1_mod_8.append(op147[8*i+1])
    
myarr_3_mod_8 = []
for i in range(30):
    myarr_3_mod_8.append(op147[8*i+3])
    
myarr_5_mod_8 = []
for i in range(30):
    myarr_5_mod_8.append(op147[8*i+5])
    
myarr_7_mod_8 = []
for i in range(30):
    myarr_7_mod_8.append(op147[8*i+7])
    
myarr_1_mod_16 = []
for i in range(15):
    myarr_1_mod_16.append(op147[16*i+1])
    
myarr_3_mod_16 = []
for i in range(15):
    myarr_3_mod_16.append(op147[16*i+3])
    
myarr_5_mod_16 = []
for i in range(15):
    myarr_5_mod_16.append(op147[16*i+5])
    
myarr_7_mod_16 = []
for i in range(15):
    myarr_7_mod_16.append(op147[16*i+7])
    
myarr_9_mod_16 = []
for i in range(15):
    myarr_9_mod_16.append(op147[16*i+9])
    
myarr_11_mod_16 = []
for i in range(15):
    myarr_11_mod_16.append(op147[16*i+11])
    
myarr_13_mod_16 = []
for i in range(15):
    myarr_13_mod_16.append(op147[16*i+13])
    
myarr_15_mod_16 = []
for i in range(15):
    myarr_15_mod_16.append(op147[16*i+15])

myarr_0_mod_32 = []
for i in range(10):
    myarr_0_mod_32.append(op147[32*i+0])
    
myarr_1_mod_32 = []
for i in range(10):
    myarr_1_mod_32.append(op147[32*i+1])
    
myarr_2_mod_32 = []
for i in range(10):
    myarr_2_mod_32.append(op147[32*i+2])
    
myarr_3_mod_32 = []
for i in range(8):
    myarr_3_mod_32.append(op147[32*i+3])
    
myarr_4_mod_32 = []
for i in range(10):
    myarr_4_mod_32.append(op147[32*i+4])
    
myarr_5_mod_32 = []
for i in range(8):
    myarr_5_mod_32.append(op147[32*i+5])
    
myarr_6_mod_32 = []
for i in range(10):
    myarr_6_mod_32.append(op147[32*i+6])
    
myarr_7_mod_32 = []
for i in range(8):
    myarr_7_mod_32.append(op147[32*i+7])
    
myarr_8_mod_32 = []
for i in range(10):
    myarr_8_mod_32.append(op147[32*i+8])
    
myarr_9_mod_32 = []
for i in range(8):
    myarr_9_mod_32.append(op147[32*i+9])

myarr_10_mod_32 = []
for i in range(8):
    myarr_10_mod_32.append(op147[32*i+10])
    
myarr_11_mod_32 = []
for i in range(8):
    myarr_11_mod_32.append(op147[32*i+11])
    
myarr_12_mod_32 = []
for i in range(8):
    myarr_12_mod_32.append(op147[32*i+12])
    
myarr_13_mod_32 = []
for i in range(8):
    myarr_13_mod_32.append(op147[32*i+13])
    
myarr_14_mod_32 = []
for i in range(8):
    myarr_14_mod_32.append(op147[32*i+14])
    
myarr_15_mod_32 = []
for i in range(8):
    myarr_15_mod_32.append(op147[32*i+15])
    
myarr_16_mod_32 = []
for i in range(8):
    myarr_16_mod_32.append(op147[32*i+16])
    
myarr_17_mod_32 = []
for i in range(9):
    myarr_17_mod_32.append(op147[32*i+17])
    
myarr_18_mod_32 = []
for i in range(8):
    myarr_18_mod_32.append(op147[32*i+18])
    
myarr_19_mod_32 = []
for i in range(8):
    myarr_19_mod_32.append(op147[32*i+19])

myarr_20_mod_32 = []
for i in range(8):
    myarr_20_mod_32.append(op147[32*i+20])
    
myarr_21_mod_32 = []
for i in range(8):
    myarr_21_mod_32.append(op147[32*i+21])
    
myarr_22_mod_32 = []
for i in range(8):
    myarr_22_mod_32.append(op147[32*i+22])
    
myarr_23_mod_32 = []
for i in range(8):
    myarr_23_mod_32.append(op147[32*i+23])
    
myarr_24_mod_32 = []
for i in range(8):
    myarr_24_mod_32.append(op147[32*i+24])
    
myarr_25_mod_32 = []
for i in range(8):
    myarr_25_mod_32.append(op147[32*i+25])
    
myarr_26_mod_32 = []
for i in range(8):
    myarr_26_mod_32.append(op147[32*i+26])
    
myarr_27_mod_32 = []
for i in range(8):
    myarr_27_mod_32.append(op147[32*i+27])
    
myarr_28_mod_32 = []
for i in range(8):
    myarr_28_mod_32.append(op147[32*i+28])
    
myarr_29_mod_32 = []
for i in range(8):
    myarr_29_mod_32.append(op147[32*i+29])
    
myarr_30_mod_32 = []
for i in range(8):
    myarr_30_mod_32.append(op147[32*i+30])
    
myarr_31_mod_32 = []
for i in range(8):
    myarr_31_mod_32.append(op147[32*i+31])

In [9]:
np.array(myarr_1_mod_4)%4==0

array([False, False,  True, False,  True,  True,  True, False,  True,
       False,  True, False, False, False,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False, False,  True,  True])

In [10]:
np.array(myarr_3_mod_4)%4==0

array([False,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
       False,  True, False,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True,  True, False,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True])

In [11]:
np.array(myarr_1_mod_8)%4==0

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True])

In [12]:
np.array(myarr_3_mod_8)%4==0

array([False, False, False,  True,  True, False,  True, False, False,
       False, False,  True, False, False,  True,  True, False, False,
       False,  True, False, False, False,  True,  True,  True, False,
        True, False,  True])

In [13]:
np.array(myarr_5_mod_8)%4==0

array([False, False,  True, False, False, False, False, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
       False, False,  True, False, False,  True, False,  True,  True,
        True, False,  True])

In [14]:
np.array(myarr_7_mod_8)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [15]:
np.array(myarr_7_mod_8)%8==0

array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True, False,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True])

In [16]:
8*1+7, op147[15], op147[15]/8

(15, 52, 13/2)

In [17]:
np.array(myarr_1_mod_16)%4==0

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False])

In [18]:
np.array(myarr_3_mod_16)%4==0

array([False, False,  True,  True, False, False, False,  True, False,
       False, False, False,  True, False, False])

In [19]:
np.array(myarr_5_mod_16)%4==0

array([False,  True, False, False,  True,  True, False, False,  True,
       False,  True, False, False,  True, False])

In [20]:
np.array(myarr_7_mod_16)%8==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [21]:
np.array(myarr_7_mod_16)%16==0

array([False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False,  True])

In [22]:
16*1+7, op147[23], op147[23]/16

(23, 232, 29/2)

In [23]:
np.array(myarr_9_mod_16)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [24]:
np.array(myarr_9_mod_16)%32==0

array([False, False, False, False, False, False,  True, False, False,
        True, False, False, False,  True, False])

In [25]:
16*1+9, op147[25], op147[25]/32

(25, 336, 21/2)

In [26]:
np.array(myarr_11_mod_16)%4==0

array([False,  True, False, False, False,  True, False,  True, False,
        True, False,  True,  True,  True,  True])

In [27]:
np.array(myarr_13_mod_16)%4==0

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False,  True,  True,  True,  True])

In [28]:
np.array(myarr_15_mod_16)%8==0

array([False,  True,  True, False,  True, False, False,  True, False,
       False, False,  True, False,  True,  True])

In [29]:
np.array(myarr_0_mod_32)%4==0

array([False,  True,  True, False,  True, False, False,  True,  True,
       False])

In [30]:
np.array(myarr_1_mod_32)%4==0

array([False,  True,  True,  True,  True,  True,  True, False,  True,
       False])

In [31]:
np.array(myarr_2_mod_32)%4==0

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True])

In [32]:
np.array(myarr_3_mod_32)%4==0

array([False,  True, False, False, False, False,  True, False])

In [33]:
np.array(myarr_4_mod_32)%4==0

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True])

In [34]:
np.array(myarr_5_mod_32)%4==0

array([False, False,  True, False,  True,  True, False, False])

In [35]:
np.array(myarr_6_mod_32)%4==0

array([False, False,  True,  True, False, False, False,  True, False,
       False])

In [36]:
np.array(myarr_7_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [37]:
np.array(myarr_8_mod_32)%4==0

array([ True, False, False, False,  True,  True, False, False,  True,
       False])

In [38]:
np.array(myarr_9_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [39]:
np.array(myarr_10_mod_32)%4==0

array([False,  True, False, False,  True,  True, False, False])

In [40]:
np.array(myarr_11_mod_32)%4==0

array([False, False, False, False, False, False,  True,  True])

In [41]:
np.array(myarr_12_mod_32)%4==0

array([False, False, False,  True,  True, False,  True, False])

In [42]:
np.array(myarr_13_mod_32)%4==0

array([False, False,  True, False,  True, False,  True,  True])

In [43]:
np.array(myarr_14_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [44]:
np.array(myarr_15_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [45]:
np.array(myarr_16_mod_32)%4==0

array([ True, False, False,  True, False, False, False,  True])

In [46]:
np.array(myarr_17_mod_32)%4==0

array([ True, False, False,  True,  True,  True,  True,  True,  True])

In [47]:
np.array(myarr_18_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [48]:
np.array(myarr_18_mod_32)%32==0

array([ True, False, False,  True,  True,  True,  True,  True])

In [49]:
32*1+18, op147[50], op147[50]/32

(50, 10672, 667/2)

In [50]:
np.array(myarr_19_mod_32)%4==0

array([False,  True, False,  True, False, False, False, False])

In [51]:
np.array(myarr_20_mod_32)%4==0

array([False, False,  True, False, False, False, False, False])

In [52]:
np.array(myarr_21_mod_32)%4==0

array([ True, False,  True, False, False, False,  True, False])

In [53]:
np.array(myarr_22_mod_32)%4==0

array([False,  True, False, False, False,  True, False,  True])

In [54]:
np.array(myarr_23_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [55]:
np.array(myarr_24_mod_32)%4==0

array([False,  True, False,  True, False,  True,  True,  True])

In [56]:
np.array(myarr_25_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [57]:
np.array(myarr_26_mod_32)%4==0

array([False, False, False, False,  True,  True, False,  True])

In [58]:
np.array(myarr_27_mod_32)%4==0

array([ True, False,  True,  True,  True,  True,  True, False])

In [59]:
np.array(myarr_28_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [60]:
np.array(myarr_29_mod_32)%4==0

array([False, False,  True,  True, False,  True,  True,  True])

In [61]:
np.array(myarr_30_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [62]:
np.array(myarr_30_mod_32)%32==0

array([False,  True,  True, False,  True, False, False,  True])

In [63]:
32*3+30, op147[126], op147[126]/32

(126, 15962192, 997637/2)

In [64]:
np.array(myarr_31_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [65]:
((f_q_q7/f_nq_nq7) * (f8^3 / (f4^2 * f16))).add_bigoh(200)

1 + 2*q + 2*q^2 + 2*q^3 + 4*q^4 + 6*q^5 + 6*q^6 + 8*q^7 + 12*q^8 + 16*q^9 + 18*q^10 + 22*q^11 + 30*q^12 + 38*q^13 + 44*q^14 + 52*q^15 + 68*q^16 + 84*q^17 + 96*q^18 + 114*q^19 + 142*q^20 + 172*q^21 + 198*q^22 + 232*q^23 + 282*q^24 + 336*q^25 + 386*q^26 + 448*q^27 + 536*q^28 + 630*q^29 + 720*q^30 + 832*q^31 + 980*q^32 + 1140*q^33 + 1300*q^34 + 1492*q^35 + 1738*q^36 + 2006*q^37 + 2278*q^38 + 2600*q^39 + 3002*q^40 + 3440*q^41 + 3892*q^42 + 4422*q^43 + 5066*q^44 + 5770*q^45 + 6508*q^46 + 7360*q^47 + 8378*q^48 + 9494*q^49 + 10672*q^50 + 12020*q^51 + 13610*q^52 + 15350*q^53 + 17200*q^54 + 19304*q^55 + 21752*q^56 + 24432*q^57 + 27298*q^58 + 30534*q^59 + 34260*q^60 + 38342*q^61 + 42720*q^62 + 47636*q^63 + 53252*q^64 + 59396*q^65 + 66004*q^66 + 73394*q^67 + 81768*q^68 + 90924*q^69 + 100796*q^70 + 111784*q^71 + 124158*q^72 + 137680*q^73 + 152274*q^74 + 168458*q^75 + 186590*q^76 + 206380*q^77 + 227756*q^78 + 251392*q^79 + 277738*q^80 + 306466*q^81 + 337520*q^82 + 371746*q^83 + 409740*q^84 + 451132*q^85 + 495878*q^86 + 545064*q^87 + 599470*q^88 + 658672*q^89 + 722670*q^90 + 792860*q^91 + 870232*q^92 + 954336*q^93 + 1045248*q^94 + 1144724*q^95 + 1254058*q^96 + 1372788*q^97 + 1501078*q^98 + 1641170*q^99 + 1794746*q^100 + 1961334*q^101 + 2141260*q^102 + 2337384*q^103 + 2551854*q^104 + 2784256*q^105 + 3035154*q^106 + 3308150*q^107 + 3606032*q^108 + 3928502*q^109 + 4276428*q^110 + 4654388*q^111 + 5065992*q^112 + 5511108*q^113 + 5991072*q^114 + 6511700*q^115 + 7077610*q^116 + 7688998*q^117 + 8347846*q^118 + 9061488*q^119 + 9835884*q^120 + 10671728*q^121 + 11571842*q^122 + 12545520*q^123 + 13600448*q^124 + 14738000*q^125 + 15962192*q^126 + 17284800*q^127 + 18715652*q^128 + 20257172*q^129 + 21914980*q^130 + 23703922*q^131 + 25636632*q^132 + 27717004*q^133 + 29952742*q^134 + 32362624*q^135 + 34962872*q^136 + 37759344*q^137 + 40762580*q^138 + 43996326*q^139 + 47481292*q^140 + 51226112*q^141 + 55245068*q^142 + 59568076*q^143 + 64221654*q^144 + 69218180*q^145 + 74576768*q^146 + 80335190*q^147 + 86527342*q^148 + 93170534*q^149 + 100290282*q^150 + 107934248*q^151 + 116145594*q^152 + 124948288*q^153 + 134376180*q^154 + 144489248*q^155 + 155342520*q^156 + 166968742*q^157 + 179412448*q^158 + 192749204*q^159 + 207049050*q^160 + 222356136*q^161 + 238728898*q^162 + 256262466*q^163 + 275045728*q^164 + 295137836*q^165 + 316615110*q^166 + 339597064*q^167 + 364196516*q^168 + 390492080*q^169 + 418582852*q^170 + 448619034*q^171 + 480743594*q^172 + 515060134*q^173 + 551697004*q^174 + 590842804*q^175 + 632678270*q^176 + 677339316*q^177 + 724991552*q^178 + 775871394*q^179 + 830207206*q^180 + 888176294*q^181 + 949991420*q^182 + 1015948872*q^183 + 1086336760*q^184 + 1161385040*q^185 + 1241366400*q^186 + 1326651804*q^187 + 1417603968*q^188 + 1514520064*q^189 + 1617748496*q^190 + 1727753024*q^191 + 1844989898*q^192 + 1969841524*q^193 + 2102751540*q^194 + 2244299380*q^195 + 2395058092*q^196 + 2555517638*q^197 + 2726241654*q^198 + 2907953352*q^199 + O(q^200)