# Ramanujan's Theta Functions

## Definitions

Let $a$ and $b$ be integers. Then we define 
$$
f(a,b) := (-q^a;q^{a+b})_{\infty}(-q^b;q^{a+b})_{\infty}(q^{a+b};q^{a+b})_{\infty}.
$$

For the ease of programming, we break the above into two different functions defined below.

$$
sf(a,b) :=  (-q^a;q^{a+b})_{\infty}
$$
and
$$
f_n := (q^{n};q^{n})_{\infty}.
$$

This implies,

$$
f(a,b) \quad = \quad sf(a,b) \; sf(b,a) \; f_{a+b}.
$$

Note that, to avoid confusion, we rename $f(a,b)$ to $ftheta(a,b)$ and $f_n$ to $f(n)$ in the following code. 

In [1]:
%display latex

In [2]:
from sage.modular.etaproducts import qexp_eta
from math import floor
import numpy as np

In [3]:
R.<q> = PowerSeriesRing(ZZ)
f1 = qexp_eta(ZZ[['q']], 2000)

def sf(a, b):
    top = floor((2000-a)/(a+b))
    base = 1
    for r in range(0,top):
        next_term = 1 + q^(a+r*(a+b))
        base = base * next_term
    return base + O(q^2000)

def f(n):
    return f1.V(n)

def ftheta(a,b):
    return sf(a,b)*sf(b,a)*f(a+b)

In [4]:
f_q_q7 = ftheta(1,7)
f_q_q7

1 + q + q^7 + q^10 + q^22 + q^27 + q^45 + q^52 + q^76 + q^85 + q^115 + q^126 + q^162 + q^175 + q^217 + q^232 + q^280 + q^297 + q^351 + q^370 + q^430 + q^451 + q^517 + q^540 + q^612 + q^637 + q^715 + q^742 + q^826 + q^855 + q^945 + q^976 + q^1072 + q^1105 + q^1207 + q^1242 + q^1350 + q^1387 + q^1501 + q^1540 + q^1660 + q^1701 + q^1827 + q^1870 - q^1993 - q^1994 - q^1999 + O(q^2000)

In [5]:
coefficients_list = f_q_q7.list()

def isodd(number):
    return number % 2 == 1

for i in range(len(coefficients_list)):
    if isodd(i):
        coefficients_list[i] = -coefficients_list[i]

f_nq_nq7 = R(coefficients_list, 2000)
f_nq_nq7

1 - q - q^7 + q^10 + q^22 - q^27 - q^45 + q^52 + q^76 - q^85 - q^115 + q^126 + q^162 - q^175 - q^217 + q^232 + q^280 - q^297 - q^351 + q^370 + q^430 - q^451 - q^517 + q^540 + q^612 - q^637 - q^715 + q^742 + q^826 - q^855 - q^945 + q^976 + q^1072 - q^1105 - q^1207 + q^1242 + q^1350 - q^1387 - q^1501 + q^1540 + q^1660 - q^1701 - q^1827 + q^1870 + q^1993 - q^1994 + q^1999 + O(q^2000)

In [6]:
op17 = ((f_q_q7/f_nq_nq7).list())[:1800]

In [7]:
myarr_0_mod_2 = []
for i in range(120):
    myarr_0_mod_2.append(op17[2*i+0])
    
myarr_1_mod_2 = []
for i in range(120):
    myarr_1_mod_2.append(op17[2*i+1])

myarr_0_mod_4 = []
for i in range(60):
    myarr_0_mod_4.append(op17[4*i])
    
myarr_1_mod_4 = []
for i in range(60):
    myarr_1_mod_4.append(op17[4*i+1])

myarr_2_mod_4 = []
for i in range(60):
    myarr_2_mod_4.append(op17[4*i+2])
    
myarr_3_mod_4 = []
for i in range(60):
    myarr_3_mod_4.append(op17[4*i+3])

myarr_0_mod_8 = []
for i in range(30):
    myarr_0_mod_8.append(op17[8*i])
    
myarr_1_mod_8 = []
for i in range(30):
    myarr_1_mod_8.append(op17[8*i+1])
    
myarr_2_mod_8 = []
for i in range(30):
    myarr_2_mod_8.append(op17[8*i+2])
    
myarr_3_mod_8 = []
for i in range(30):
    myarr_3_mod_8.append(op17[8*i+3])

myarr_4_mod_8 = []
for i in range(30):
    myarr_4_mod_8.append(op17[8*i+4])
    
myarr_5_mod_8 = []
for i in range(30):
    myarr_5_mod_8.append(op17[8*i+5])
    
myarr_6_mod_8 = []
for i in range(30):
    myarr_6_mod_8.append(op17[8*i+6])
    
myarr_7_mod_8 = []
for i in range(30):
    myarr_7_mod_8.append(op17[8*i+7])

myarr_0_mod_16 = []
for i in range(15):
    myarr_0_mod_16.append(op17[16*i+1])
    
myarr_1_mod_16 = []
for i in range(15):
    myarr_1_mod_16.append(op17[16*i+1])
    
myarr_2_mod_16 = []
for i in range(15):
    myarr_2_mod_16.append(op17[16*i+2])
    
myarr_3_mod_16 = []
for i in range(15):
    myarr_3_mod_16.append(op17[16*i+3])
    
myarr_4_mod_16 = []
for i in range(15):
    myarr_4_mod_16.append(op17[16*i+4])
    
myarr_5_mod_16 = []
for i in range(15):
    myarr_5_mod_16.append(op17[16*i+5])
    
myarr_6_mod_16 = []
for i in range(15):
    myarr_6_mod_16.append(op17[16*i+6])
    
myarr_7_mod_16 = []
for i in range(15):
    myarr_7_mod_16.append(op17[16*i+7])
    
myarr_8_mod_16 = []
for i in range(15):
    myarr_8_mod_16.append(op17[16*i+8])
    
myarr_9_mod_16 = []
for i in range(15):
    myarr_9_mod_16.append(op17[16*i+9])
    
myarr_10_mod_16 = []
for i in range(15):
    myarr_10_mod_16.append(op17[16*i+10])
    
myarr_11_mod_16 = []
for i in range(15):
    myarr_11_mod_16.append(op17[16*i+11])
    
myarr_12_mod_16 = []
for i in range(15):
    myarr_12_mod_16.append(op17[16*i+12])
    
myarr_13_mod_16 = []
for i in range(15):
    myarr_13_mod_16.append(op17[16*i+13])
    
myarr_14_mod_16 = []
for i in range(15):
    myarr_14_mod_16.append(op17[16*i+14])
    
myarr_15_mod_16 = []
for i in range(15):
    myarr_15_mod_16.append(op17[16*i+15])

myarr_0_mod_32 = []
for i in range(10):
    myarr_0_mod_32.append(op17[32*i])
    
myarr_1_mod_32 = []
for i in range(10):
    myarr_1_mod_32.append(op17[32*i+1])
    
myarr_2_mod_32 = []
for i in range(10):
    myarr_2_mod_32.append(op17[32*i+2])
    
myarr_3_mod_32 = []
for i in range(8):
    myarr_3_mod_32.append(op17[32*i+3])
    
myarr_4_mod_32 = []
for i in range(10):
    myarr_4_mod_32.append(op17[32*i+4])
    
myarr_5_mod_32 = []
for i in range(8):
    myarr_5_mod_32.append(op17[32*i+5])
    
myarr_6_mod_32 = []
for i in range(10):
    myarr_6_mod_32.append(op17[32*i+6])
    
myarr_7_mod_32 = []
for i in range(8):
    myarr_7_mod_32.append(op17[32*i+7])
    
myarr_8_mod_32 = []
for i in range(10):
    myarr_8_mod_32.append(op17[32*i+8])
    
myarr_9_mod_32 = []
for i in range(8):
    myarr_9_mod_32.append(op17[32*i+9])
    
myarr_10_mod_32 = []
for i in range(10):
    myarr_10_mod_32.append(op17[32*i+10])
    
myarr_11_mod_32 = []
for i in range(8):
    myarr_11_mod_32.append(op17[32*i+11])
    
myarr_12_mod_32 = []
for i in range(10):
    myarr_12_mod_32.append(op17[32*i+12])
    
myarr_13_mod_32 = []
for i in range(8):
    myarr_13_mod_32.append(op17[32*i+13])
    
myarr_14_mod_32 = []
for i in range(10):
    myarr_14_mod_32.append(op17[32*i+14])
    
myarr_15_mod_32 = []
for i in range(8):
    myarr_15_mod_32.append(op17[32*i+15])
    
myarr_16_mod_32 = []
for i in range(10):
    myarr_16_mod_32.append(op17[32*i+16])
    
myarr_17_mod_32 = []
for i in range(9):
    myarr_17_mod_32.append(op17[32*i+17])
    
myarr_18_mod_32 = []
for i in range(30):
    myarr_18_mod_32.append(op17[32*i+18])
    
myarr_19_mod_32 = []
for i in range(8):
    myarr_19_mod_32.append(op17[32*i+19])

myarr_20_mod_32 = []
for i in range(8):
    myarr_20_mod_32.append(op17[32*i+20])
    
myarr_21_mod_32 = []
for i in range(8):
    myarr_21_mod_32.append(op17[32*i+21])
    
myarr_22_mod_32 = []
for i in range(8):
    myarr_22_mod_32.append(op17[32*i+22])
    
myarr_23_mod_32 = []
for i in range(8):
    myarr_23_mod_32.append(op17[32*i+23])
    
myarr_24_mod_32 = []
for i in range(8):
    myarr_24_mod_32.append(op17[32*i+24])
    
myarr_25_mod_32 = []
for i in range(8):
    myarr_25_mod_32.append(op17[32*i+25])
    
myarr_26_mod_32 = []
for i in range(8):
    myarr_26_mod_32.append(op17[32*i+26])
    
myarr_27_mod_32 = []
for i in range(8):
    myarr_27_mod_32.append(op17[32*i+27])
    
myarr_28_mod_32 = []
for i in range(8):
    myarr_28_mod_32.append(op17[32*i+28])
    
myarr_29_mod_32 = []
for i in range(8):
    myarr_29_mod_32.append(op17[32*i+29])
    
myarr_30_mod_32 = []
for i in range(8):
    myarr_30_mod_32.append(op17[32*i+30])
    
myarr_31_mod_32 = []
for i in range(8):
    myarr_31_mod_32.append(op17[32*i+31])

In [8]:
np.array(myarr_0_mod_2)%2==0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [9]:
np.array(myarr_1_mod_2)%2==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [10]:
np.array(myarr_0_mod_4)%4==0

array([False, False, False, False, False, False, False,  True, False,
        True, False, False, False, False,  True,  True, False,  True,
        True, False, False,  True, False,  True, False,  True, False,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True, False, False,  True, False,  True,  True, False, False,
       False,  True,  True, False, False,  True,  True, False, False,
        True,  True,  True,  True, False, False])

In [11]:
np.array(myarr_1_mod_4)%4==0

array([False, False,  True, False,  True,  True,  True, False,  True,
       False,  True, False, False, False,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False, False,  True,  True])

In [12]:
np.array(myarr_2_mod_4)%4==0

array([False, False, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True, False, False,  True, False,  True, False,
        True,  True, False, False,  True,  True, False,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True, False,
       False,  True,  True,  True, False,  True])

In [13]:
np.array(myarr_3_mod_4)%4==0

array([False,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
       False,  True, False,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True,  True, False,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True])

In [14]:
np.array(myarr_0_mod_8)%4==0

array([False, False, False, False, False, False, False,  True, False,
        True, False, False, False, False,  True,  True, False,  True,
        True, False, False,  True, False,  True, False,  True, False,
        True,  True, False])

In [15]:
np.array(myarr_1_mod_8)%4==0

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True])

In [16]:
np.array(myarr_2_mod_8)%4==0

array([False, False,  True, False,  True,  True,  True, False,  True,
       False,  True, False, False, False,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True, False])

In [17]:
np.array(myarr_3_mod_8)%4==0

array([False, False, False,  True,  True, False,  True, False, False,
       False, False,  True, False, False,  True,  True, False, False,
       False,  True, False, False, False,  True,  True,  True, False,
        True, False,  True])

In [18]:
np.array(myarr_4_mod_8)%4==0

array([False, False, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True, False, False,  True, False,  True, False,
        True,  True, False])

In [19]:
np.array(myarr_5_mod_8)%4==0

array([False, False,  True, False, False, False, False, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
       False, False,  True, False, False,  True, False,  True,  True,
        True, False,  True])

In [20]:
np.array(myarr_6_mod_8)%4==0

array([False,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
       False,  True, False,  True,  True,  True, False,  True, False,
        True,  True,  True])

In [21]:
np.array(myarr_7_mod_8)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [22]:
np.array(myarr_7_mod_8)%8==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True,  True,  True])

In [23]:
8*2+7, op17[23], op17[23]/8

(23, 52, 13/2)

In [24]:
np.array(myarr_0_mod_16)%4==0

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False])

In [25]:
np.array(myarr_1_mod_16)%4==0

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False])

In [26]:
np.array(myarr_3_mod_16)%4==0

array([False, False,  True,  True, False, False, False,  True, False,
       False, False, False,  True, False, False])

In [27]:
np.array(myarr_4_mod_16)%4==0

array([False, False,  True, False,  True,  True,  True, False,  True,
       False,  True, False, False, False,  True])

In [28]:
np.array(myarr_5_mod_16)%4==0

array([False,  True, False, False,  True,  True, False, False,  True,
       False,  True, False, False,  True, False])

In [29]:
np.array(myarr_6_mod_16)%4==0

array([False, False, False,  True,  True, False,  True, False, False,
       False, False,  True, False, False,  True])

In [30]:
np.array(myarr_7_mod_16)%8==0

array([False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False,  True])

In [31]:
np.array(myarr_8_mod_16)%4==0

array([False, False, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True, False])

In [32]:
np.array(myarr_9_mod_16)%8==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [33]:
np.array(myarr_9_mod_16)%16==0

array([False,  True,  True, False, False, False,  True, False,  True,
       False,  True,  True, False,  True, False])

In [34]:
16*3+9, op17[57], op17[57]/16

(57, 2232, 279/2)

In [35]:
np.array(myarr_10_mod_16)%4==0

array([False, False,  True, False, False, False, False, False,  True,
        True,  True,  True, False, False, False])

In [36]:
np.array(myarr_11_mod_16)%4==0

array([False,  True, False, False, False,  True, False,  True, False,
        True, False,  True,  True,  True,  True])

In [37]:
np.array(myarr_12_mod_16)%4==0

array([False,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False])

In [38]:
np.array(myarr_13_mod_16)%4==0

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False,  True,  True,  True,  True])

In [39]:
np.array(myarr_14_mod_16)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [40]:
np.array(myarr_14_mod_16)%8==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True,  True])

In [41]:
16*2+14, op17[46], op17[46]/8

(46, 716, 179/2)

In [42]:
np.array(myarr_15_mod_16)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [43]:
np.array(myarr_15_mod_16)%32==0

array([False, False, False, False,  True,  True,  True, False, False,
        True,  True, False,  True, False,  True])

In [44]:
16*1+15, op17[31], op17[31]/32

(31, 144, 9/2)

In [45]:
np.array(myarr_0_mod_32)%4==0

array([False, False, False, False, False, False, False,  True, False,
        True])

In [46]:
np.array(myarr_1_mod_32)%4==0

array([False,  True,  True,  True,  True,  True,  True, False,  True,
       False])

In [47]:
np.array(myarr_2_mod_32)%4==0

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True])

In [48]:
np.array(myarr_3_mod_32)%4==0

array([False,  True, False, False, False, False,  True, False])

In [49]:
np.array(myarr_4_mod_32)%4==0

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True])

In [50]:
np.array(myarr_5_mod_32)%4==0

array([False, False,  True, False,  True,  True, False, False])

In [51]:
np.array(myarr_6_mod_32)%4==0

array([False, False,  True,  True, False, False, False,  True, False,
       False])

In [52]:
np.array(myarr_7_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [53]:
np.array(myarr_7_mod_32)%8==0

array([False, False, False, False,  True, False, False,  True])

In [54]:
np.array(myarr_8_mod_32)%4==0

array([False, False,  True, False,  True,  True,  True, False,  True,
       False])

In [55]:
np.array(myarr_9_mod_32)%8==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [56]:
np.array(myarr_10_mod_32)%4==0

array([False,  True, False, False,  True,  True, False, False,  True,
       False])

In [57]:
np.array(myarr_11_mod_32)%4==0

array([False, False, False, False, False, False,  True,  True])

In [58]:
np.array(myarr_12_mod_32)%4==0

array([False, False, False,  True,  True, False,  True, False, False,
       False])

In [59]:
np.array(myarr_13_mod_32)%4==0

array([False, False,  True, False,  True, False,  True,  True])

In [60]:
np.array(myarr_14_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [61]:
np.array(myarr_15_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [62]:
np.array(myarr_16_mod_32)%4==0

array([False, False, False,  True,  True, False, False,  True,  True,
       False])

In [63]:
np.array(myarr_17_mod_32)%4==0

array([ True, False, False,  True,  True,  True,  True,  True,  True])

In [64]:
np.array(myarr_18_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [65]:
np.array(myarr_18_mod_32)%32==0

array([ True, False, False,  True,  True,  True,  True,  True, False,
       False, False, False,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True, False,  True, False, False,
        True, False,  True])

In [66]:
32*1+18, op17[50], op17[50]/32

(50, 1168, 73/2)

In [67]:
np.array(myarr_19_mod_32)%4==0

array([False,  True, False,  True, False, False, False, False])

In [68]:
np.array(myarr_20_mod_32)%4==0

array([False, False,  True, False, False, False, False, False])

In [69]:
np.array(myarr_21_mod_32)%4==0

array([ True, False,  True, False, False, False,  True, False])

In [70]:
np.array(myarr_22_mod_32)%4==0

array([False,  True, False, False, False,  True, False,  True])

In [71]:
np.array(myarr_23_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [72]:
np.array(myarr_24_mod_32)%4==0

array([False,  True, False,  True, False,  True,  True,  True])

In [73]:
np.array(myarr_25_mod_32)%8==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [74]:
np.array(myarr_26_mod_32)%4==0

array([False, False, False, False,  True,  True, False,  True])

In [75]:
np.array(myarr_27_mod_32)%4==0

array([ True, False,  True,  True,  True,  True,  True, False])

In [76]:
np.array(myarr_28_mod_32)%4==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [77]:
np.array(myarr_28_mod_32)%8==0

array([False,  True, False,  True, False,  True, False,  True])

In [78]:
32*2+28, op17[92], op17[92]/8

(92, 37220, 9305/2)

In [79]:
np.array(myarr_29_mod_32)%4==0

array([False, False,  True,  True, False,  True,  True,  True])

In [80]:
np.array(myarr_30_mod_32)%8==0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [81]:
np.array(myarr_30_mod_32)%16==0

array([False,  True,  True, False,  True, False, False,  True])

In [82]:
32*3+30, op17[126], op17[126]/16

(126, 383608, 47951/2)

In [83]:
np.array(myarr_31_mod_32)%16==0

array([ True,  True,  True,  True,  True,  True,  True,  True])